import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

export default function Approvals() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); axiosClient.get('/operations/approvals').then(({ data }) => { setRows(data.data); setError(''); }).catch(() => setError('Could not load approvals. Your role may not have review access.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const decide = async (id, outcome) => { const reason = window.prompt(`Reason for ${outcome.toLowerCase()}:`); if (!reason) return; try { await axiosClient.patch(`/operations/approvals/${id}`, { outcome, reason }); load(); } catch { setError('Decision could not be saved. A reason is required.'); } };
  return <div className="space-y-4"><p className="text-sm text-muted">Every material recommendation requires an authorised, auditable human decision.</p><LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !rows.length}><Table headers={['Request', 'Recommendation', 'AI model', 'Current decision', 'Reason', 'Actions']}>{rows.map((row) => <tr key={row.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-medium">{row.purchaseRequest?.lines?.map((line) => line.item.name).join(', ') || 'Operational decision'}</p><p className="text-xs text-muted">{new Date(row.createdAt).toLocaleString()}</p></td><td className="px-4 py-3">{row.purchaseRequest?.lines?.map((line) => `${line.quantity} × ${line.item.sku}`).join(', ') || '—'}</td><td className="px-4 py-3">{row.aiRun?.modelVersion?.version || 'Rule-based'}</td><td className="px-4 py-3"><StatusBadge value={row.outcome} /></td><td className="px-4 py-3 text-ink/70">{row.reason}</td><td className="px-4 py-3 space-x-2">{row.outcome === 'PENDING' && <><button onClick={() => decide(row.id, 'APPROVED')} className="text-xs text-status-ok hover:underline">Approve</button><button onClick={() => decide(row.id, 'REJECTED')} className="text-xs text-status-critical hover:underline">Reject</button><button onClick={() => decide(row.id, 'DEFERRED')} className="text-xs text-primary hover:underline">Defer</button></>}</td></tr>)}</Table></LoadingErrorEmpty></div>;
}
