import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, Table } from '../components/common/OperationalUI';

export default function AuditLogs() {
  const [logs, setLogs] = useState([]); const [action, setAction] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { setLoading(true); axiosClient.get('/audit-logs', { params: { action: action || undefined, pageSize: 100 } }).then(({ data }) => { setLogs(data.data); setError(''); }).catch(() => setError('Could not load audit records. Governance-role access is required.')).finally(() => setLoading(false)); }, [action]);
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><label className="text-sm text-muted">Action <select value={action} onChange={(e) => setAction(e.target.value)} className="ml-2 rounded border border-border bg-surface px-3 py-2"><option value="">All actions</option><option>LOGIN</option><option>CREATE</option><option>UPDATE</option><option>EXPORT</option><option>AI_RUN</option><option>APPROVED</option><option>REJECTED</option><option>DEFERRED</option></select></label><p className="text-xs text-muted">Append-only records; normal users cannot modify them.</p></div><LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !logs.length}><Table headers={['Time', 'Actor', 'Action', 'Entity', 'Outcome', 'Metadata']}>{logs.map((log) => <tr key={log.id} className="border-b border-border"><td className="px-4 py-3 text-xs">{new Date(log.createdAt).toLocaleString()}</td><td className="px-4 py-3">{log.actor?.name || 'System'}<p className="text-xs text-muted">{log.actor?.email}</p></td><td className="px-4 py-3 font-mono text-xs">{log.action}</td><td className="px-4 py-3">{log.entityType || '—'}</td><td className="px-4 py-3">{log.outcome || '—'}</td><td className="max-w-xs truncate px-4 py-3 text-xs text-muted" title={JSON.stringify(log.metadata)}>{log.metadata ? JSON.stringify(log.metadata) : '—'}</td></tr>)}</Table></LoadingErrorEmpty></div>;
}
