import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

export default function Forecasting() {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [result, setResult] = useState(null);
  useEffect(() => { axiosClient.get('/items', { params: { pageSize: 100 } }).then(({ data }) => setItems(data.data)).catch(() => setError('Could not load items for forecasting.')).finally(() => setLoading(false)); }, []);
  const generate = async (item) => { setResult({ loading: true, item: item.name }); try { const { data } = await axiosClient.post(`/items/${item.id}/forecasts/generate`); setResult({ item: item.name, ...data.data }); } catch { setResult({ error: 'Forecast could not be generated. Ensure demand history is available.', item: item.name }); } };
  return <div className="space-y-4">{result && <div className="rounded-lg border border-border bg-surface p-4"><p className="font-medium text-ink">{result.loading ? `Generating forecast for ${result.item}…` : result.error || `Forecast generated for ${result.item}`}</p>{result.forecast && <><p className="mt-1 text-sm text-ink/70">{result.explanation}</p><p className="mt-2 font-mono text-sm">Demand: {result.forecast.pointForecast} · Confidence: {Math.round((result.forecast.confidence || 0) * 100)}% · Model: {result.forecast.modelVersion.version}</p></>}</div>}<LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !items.length}><Table headers={['Item', 'Category', 'Stock', 'Action']}>{items.map((item) => <tr key={item.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-medium">{item.name}</p><p className="font-mono text-xs text-muted">{item.sku}</p></td><td className="px-4 py-3">{item.category.replaceAll('_', ' ')}</td><td className="px-4 py-3">{item.stockBalances.reduce((sum, balance) => sum + Number(balance.onHandQty), 0)}</td><td className="px-4 py-3"><button onClick={() => generate(item)} className="rounded bg-primary px-3 py-1.5 text-xs font-medium text-white">Generate forecast</button></td></tr>)}</Table></LoadingErrorEmpty></div>;
}
