import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

export default function ItemDetail() {
  const [items, setItems] = useState([]); const [selected, setSelected] = useState(null); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = () => { setLoading(true); axiosClient.get('/items', { params: { pageSize: 100, search: search || undefined } }).then(({ data }) => { setItems(data.data); setError(''); }).catch(() => setError('Could not load inventory items.')).finally(() => setLoading(false)); };
  useEffect(load, [search]);
  const openItem = async (id) => { try { const { data } = await axiosClient.get(`/items/${id}`); setSelected(data.data); } catch { setError('Could not load item details.'); } };
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search item or SKU" className="rounded-md border border-border bg-surface px-3 py-2 text-sm" /><span className="text-sm text-muted">{items.length} matching items</span></div><LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !items.length}><Table headers={['Item', 'Category', 'On hand', 'Reserved', 'Action']}>{items.map((item) => <tr key={item.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-medium">{item.name}</p><p className="font-mono text-xs text-muted">{item.sku}</p></td><td className="px-4 py-3">{item.category.replaceAll('_', ' ')}</td><td className="px-4 py-3 font-mono">{item.stockBalances.reduce((sum, balance) => sum + Number(balance.onHandQty), 0)}</td><td className="px-4 py-3 font-mono">{item.stockBalances.reduce((sum, balance) => sum + Number(balance.reservedQty), 0)}</td><td className="px-4 py-3"><button onClick={() => openItem(item.id)} className="text-xs text-primary hover:underline">View details</button></td></tr>)}</Table></LoadingErrorEmpty>{selected && <section className="rounded-lg border border-border bg-surface p-5"><div className="flex justify-between gap-4"><div><h2 className="font-display text-lg">{selected.name}</h2><p className="font-mono text-xs text-muted">{selected.sku}</p></div><button onClick={() => setSelected(null)} className="text-sm text-primary">Close</button></div><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-3"><div><p className="text-xs uppercase text-muted">Replenishment</p><p>Safety {selected.replenishmentParams?.[0]?.safetyStock ?? '—'} · Reorder point {selected.replenishmentParams?.[0]?.reorderPoint ?? '—'}</p></div><div><p className="text-xs uppercase text-muted">Lots & locations</p>{selected.stockBalances.map((balance) => <p key={balance.id}>{balance.location.name}: {balance.onHandQty} on hand, {balance.reservedQty} reserved</p>)}</div><div><p className="text-xs uppercase text-muted">Latest forecasts</p>{selected.forecasts.length ? selected.forecasts.map((forecast) => <p key={forecast.id}>{forecast.pointForecast} units · <StatusBadge value={forecast.status} /></p>) : <p>No forecasts yet.</p>}</div></div></section>}</div>;
}
