import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

export default function Recommendations() {
  const [rows, setRows] = useState([]); const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState('');
  useEffect(() => { Promise.all([axiosClient.get('/operations/replenishment'), axiosClient.get('/operations/suppliers/scorecards')]).then(([planning, supplierData]) => { setRows(planning.data.data.filter((row) => row.recommendedQty > 0)); setSuppliers(supplierData.data.data); }).finally(() => setLoading(false)); }, []);
  const request = async (row) => { try { await axiosClient.post('/operations/purchase-requests', { itemId: row.id, quantity: row.recommendedQty }); setNotice(`Recommendation sent for approval: ${row.name}.`); } catch { setNotice('Could not create the approval request.'); } };
  return <div className="space-y-5">{notice && <p className="rounded bg-status-okBg p-3 text-sm text-status-ok">{notice}</p>}<section><h2 className="mb-2 font-display text-lg">Reorder recommendations</h2><LoadingErrorEmpty loading={loading} empty={!loading && !rows.length}><Table headers={['Item', 'Risk', 'Recommended reorder', 'Forecast evidence', 'Action']}>{rows.map((row) => <tr key={row.id} className="border-b border-border"><td className="px-4 py-3"><p className="font-medium">{row.name}</p><p className="font-mono text-xs text-muted">{row.sku}</p></td><td className="px-4 py-3"><StatusBadge value={row.status} /></td><td className="px-4 py-3 font-mono">{row.recommendedQty} units</td><td className="px-4 py-3">Demand {row.forecastDemand || 'unavailable'} · Confidence {row.forecastConfidence ? `${Math.round(row.forecastConfidence * 100)}%` : 'pending'}</td><td className="px-4 py-3"><button onClick={() => request(row)} className="rounded bg-primary px-3 py-1.5 text-xs text-white">Send for review</button></td></tr>)}</Table></LoadingErrorEmpty></section><section><h2 className="mb-2 font-display text-lg">Supplier scorecards</h2><Table headers={['Supplier', 'Lead time', 'Risk', 'Open orders', 'Scorecard']}>{suppliers.map((supplier) => <tr key={supplier.id} className="border-b border-border"><td className="px-4 py-3 font-medium">{supplier.name}</td><td className="px-4 py-3">{supplier.leadTimeDays ?? '—'} days</td><td className="px-4 py-3"><StatusBadge value={supplier.riskScore} /></td><td className="px-4 py-3">{supplier.openOrders}</td><td className="px-4 py-3 text-xs">{supplier.scorecard ? Object.entries(supplier.scorecard).map(([key, value]) => `${key}: ${value}`).join(' · ') : 'No scorecard'}</td></tr>)}</Table></section></div>;
}
