import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

export default function Replenishment() {
  const [rows, setRows] = useState([]); const [multiplier, setMultiplier] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); try { const { data } = await axiosClient.get('/operations/replenishment', { params: { demandMultiplier: multiplier } }); setRows(data.data); setError(''); } catch { setError('Could not load replenishment planning.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [multiplier]);
  const createRequest = async (row) => { try { await axiosClient.post('/operations/purchase-requests', { itemId: row.id, quantity: row.recommendedQty || row.reorderQty || 1 }); setNotice(`Purchase request created for ${row.name}.`); } catch { setNotice('Could not create the purchase request. Check your role and retry.'); } };
  return <div className="space-y-5"><div className="rounded-lg border border-border bg-surface p-4"><label className="text-sm font-medium text-ink">Scenario demand multiplier <input className="ml-3 w-20 rounded border border-border px-2 py-1" type="number" min="0.25" max="3" step="0.25" value={multiplier} onChange={(e) => setMultiplier(e.target.value)} /></label><p className="mt-1 text-xs text-muted">Adjust demand to explore a planning scenario. No stock or order is changed automatically.</p></div>{notice && <p className="rounded-md bg-status-okBg p-3 text-sm text-status-ok">{notice}</p>}<LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !rows.length}><Table headers={['Item', 'Available', 'Forecast', 'Lead time', 'Recommendation', 'Status', 'Action']}>{rows.map((row) => <tr key={row.id} className="border-b border-border last:border-0"><td className="px-4 py-3"><p className="font-medium">{row.name}</p><p className="font-mono text-xs text-muted">{row.sku}</p></td><td className="px-4 py-3 font-mono">{row.available}</td><td className="px-4 py-3 font-mono">{row.forecastDemand || '—'}</td><td className="px-4 py-3">{row.leadTimeDays ?? '—'} days</td><td className="px-4 py-3">{row.recommendedQty ? `${row.recommendedQty} units` : 'No action'}</td><td className="px-4 py-3"><StatusBadge value={row.status} /></td><td className="px-4 py-3">{row.recommendedQty > 0 && <button onClick={() => createRequest(row)} className="rounded bg-primary px-3 py-1.5 text-xs font-medium text-white">Request review</button>}</td></tr>)}</Table></LoadingErrorEmpty></div>;
}
