import { useEffect, useState } from 'react';
import axiosClient from '../api/axiosClient';
import { LoadingErrorEmpty, StatusBadge, Table } from '../components/common/OperationalUI';

const ROLES = ['ADMIN', 'PROCUREMENT_MANAGER', 'INVENTORY_PLANNER', 'WAREHOUSE_USER', 'SUPPLIER', 'FINANCE_REVIEWER'];
export default function UserManagement() {
  const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [form, setForm] = useState({ name: '', email: '', password: '', role: 'INVENTORY_PLANNER' }); const [showForm, setShowForm] = useState(false);
  const load = () => { setLoading(true); axiosClient.get('/users').then(({ data }) => { setUsers(data.data); setError(''); }).catch(() => setError('Could not load users. Administrator access is required.')).finally(() => setLoading(false)); };
  useEffect(load, []);
  const create = async (event) => { event.preventDefault(); try { await axiosClient.post('/users', form); setForm({ name: '', email: '', password: '', role: 'INVENTORY_PLANNER' }); setShowForm(false); load(); } catch (requestError) { setError(requestError.response?.data?.error?.message || 'Could not create user.'); } };
  const setStatus = async (user, status) => { try { await axiosClient.patch(`/users/${user.id}/status`, { status }); load(); } catch { setError('Could not update account status.'); } };
  return <div className="space-y-4"><div className="flex justify-between gap-4"><p className="text-sm text-muted">Manage organisation members and least-privilege operational roles.</p><button onClick={() => setShowForm((value) => !value)} className="rounded bg-primary px-4 py-2 text-sm text-white">{showForm ? 'Cancel' : 'Add user'}</button></div>{showForm && <form onSubmit={create} className="grid grid-cols-1 gap-3 rounded-lg border border-border bg-surface p-4 md:grid-cols-4"><input required placeholder="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="rounded border border-border px-3 py-2 text-sm" /><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="rounded border border-border px-3 py-2 text-sm" /><input required minLength="8" type="password" placeholder="Temporary password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="rounded border border-border px-3 py-2 text-sm" /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="rounded border border-border px-3 py-2 text-sm">{ROLES.map((role) => <option key={role}>{role}</option>)}</select><button className="rounded bg-primary px-4 py-2 text-sm text-white md:col-span-4">Create user</button></form>}<LoadingErrorEmpty loading={loading} error={error} empty={!loading && !error && !users.length}><Table headers={['User', 'Role', 'Status', 'Last login', 'Account action']}>{users.map((user) => <tr key={user.id} className="border-b border-border"><td className="px-4 py-3"><p className="font-medium">{user.name}</p><p className="text-xs text-muted">{user.email}</p></td><td className="px-4 py-3">{user.role.replaceAll('_', ' ')}</td><td className="px-4 py-3"><StatusBadge value={user.status} /></td><td className="px-4 py-3">{user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : 'Never'}</td><td className="px-4 py-3"><button onClick={() => setStatus(user, user.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE')} className="text-xs text-primary hover:underline">{user.status === 'ACTIVE' ? 'Deactivate' : 'Activate'}</button></td></tr>)}</Table></LoadingErrorEmpty></div>;
}
